<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tasks extends Model
{
    protected $table = 'tasks';
    protected $primaryKey = 'id';

    protected $fillable = [
        "post_key",
        "result_url",
        "result_title",
        "task_id",
        "loc_id",
        "req_id"
    ];

    protected $hidden = [
        'created_at',
        'updated_at',
    ];

    //Обновление выполненый задач
    //Можно было бы искать по стрингам через лайк и обновлять
    //Но проще удалить и записать в моей ситуации
    public function updateFromArray(array $attributes = [])
    {
        foreach ($attributes as $k => $attribute){
            if(in_array($k , $this->fillable)){
                $this->$k = $attribute;
            }
        }
        return $this->update(); // TODO: Change the autogenerated stub
    }
}
